### ISSUE TITLE
Baseline: Render

### ISSUE THREAD

**Issue by DIYer22** [RPC-Dataset/RPC-Leaderboard#2]
## Baseline: Render result on RPC-Dataset
|    level |          method |   cAcc |  mCIoU |  ACD | mCCD |  mAP50 |   mmAP |
|     ---: |            ---: |   ---: |   ---: | ---: | ---: |   ---: |   ---: |
|     easy | Baseline: Render | 63.19% | 90.64% | 0.72 | 0.11 | 96.21% | 77.65% |
|   medium | Baseline: Render | 43.02% | 90.64% | 1.24 | 0.11 | 95.83% | 72.53% |
|     hard | Baseline: Render | 31.01% | 90.41% | 1.77 |  0.1 | 95.18% | 71.56% |
| averaged | Baseline: Render |  45.6% | 90.58% | 1.25 |  0.1 |  95.5% | 72.76% |

## Description
RPC's Baseline: Render

**Comment by robot520** [comment]
My Questions:
1. What is the object counting and detection framework used in baselines of your paper?
2. In addition, where are the real backgound images comes for synthetic check-out image generation?

**Comment by DIYer22** [comment]
Answer:
1. We using [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark/) as detection framework.
1. Background images are [here](https://github.com/RPC-Dataset/RPC-Dataset.github.io/tree/master/imgs/backgrounds).

**Comment by ShihuaiXu** [comment]
@robot520 
Sir, would like to show the detail of your method? I am interested in it, especially how to get the syn and render images
