### ISSUE TITLE
问一下这个train数据集为什么不用单一的背景呢？

### ISSUE THREAD

**Issue by andeyeluguo** [RPC-Dataset/RPC-Leaderboard#5]
首先感谢开源这个数据集，但是在复现的时候发现需要显著性检测和随机条件场等理论把图像的mask扣出来，感觉太麻烦，如果是单一背景（比如全黑全白），就比较容易抠出来，不知道当时设计的时候是怎么打算的？

**Comment by DIYer22** [comment]
`RPC-Leaderboard/Issues` is a place to  submit results on the RPC dataset. 

If you have questions about the RPC article or project, please open a issue [here](https://github.com/RPC-Dataset/RPC-Dataset.github.io/issues).
